version: '3.8'

services:
  frontend:
    build:
      context: ./front
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    container_name: frontend
    depends_on:
      - backend
    links:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    container_name: backend
    