name: CI/CD with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Images
        run: |
          # Extract service names from docker compose.yml
          services=$(docker compose config --services)
          
          for service in $services; do
            image_name="${{ secrets.DOCKER_USERNAME }}/my-chat-app-${service}"
            
            # Build the service
            docker compose build $service

            # Tag the image
            docker tag my-chat-app_${service}:latest $image_name:latest
            
            # Push to Docker Hub
            docker push $image_name:latest
            
            echo "Pushed $image_name:latest to Docker Hub"
          done

      - name: Verify Deployment
        run: docker compose images
